"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NumberCard = void 0;
var NumberCard;
(function (NumberCard) {
    NumberCard["ONE"] = "ONE";
    NumberCard["TWO"] = "TWO";
    NumberCard["THREE"] = "THREE";
    NumberCard["FOUR"] = "FOUR";
    NumberCard["FIVE"] = "FIVE";
    NumberCard["SIX"] = "SIX";
    NumberCard["SEVEN"] = "SEVEN";
    NumberCard["EIGHT"] = "EIGHT";
    NumberCard["NINE"] = "NINE";
    NumberCard["TEN"] = "TEN";
    NumberCard["JACK"] = "JACK";
    NumberCard["QUEEN"] = "QUEEN";
    NumberCard["KING"] = "KING";
    NumberCard["ACE"] = "ACE";
    NumberCard["BIGTWO"] = "BIGTWO";
})(NumberCard || (exports.NumberCard = NumberCard = {}));
